let {
	areaValidator, 
	areainfraestructuraValidator, 
	cargoValidator, 
	categoriaservicioValidator, 
	clienteValidator, 
	clientedetalleValidator, 
	divisionValidator, 
	divisionareaValidator, 
	divisionnegocioValidator, 
	estadoclienteValidator, 
	estadoordenValidator, 
	estadotrabajosValidator, 
	infraestructuraValidator, 
	infraestructuradetalleValidator, 
	infraestructuraubicacionValidator, 
	negocioValidator, 
	negociodetalleValidator, 
	negocioordenValidator, 
	negocioservicioValidator, 
	ordenValidator, 
	ordendetalleValidator, 
	ordenservicioValidator, 
	servicioValidator, 
	serviciodetalleValidator, 
	tipoareaValidator, 
	tipocargoValidator, 
	tipoclienteValidator, 
	tipodivisionValidator, 
	tipoequipamientoValidator, 
	tipoinfraestructuraValidator, 
	tiponegocioValidator, 
	tipoordenValidator, 
	tiposervicioValidator, 
	tipoubicacionValidator, 
	tipousuarioValidator, 
	ubicacionValidator, 
	usuarioValidator, 
	usuariologinValidator, 
} = require('./joi')

let validator = {
	areaValidator: (payload) => areaValidator(payload),
	areainfraestructuraValidator: (payload) => areainfraestructuraValidator(payload),
	cargoValidator: (payload) => cargoValidator(payload),
	categoriaservicioValidator: (payload) => categoriaservicioValidator(payload),
	clienteValidator: (payload) => clienteValidator(payload),
	clientedetalleValidator: (payload) => clientedetalleValidator(payload),
	divisionValidator: (payload) => divisionValidator(payload),
	divisionareaValidator: (payload) => divisionareaValidator(payload),
	divisionnegocioValidator: (payload) => divisionnegocioValidator(payload),
	estadoclienteValidator: (payload) => estadoclienteValidator(payload),
	estadoordenValidator: (payload) => estadoordenValidator(payload),
	estadotrabajosValidator: (payload) => estadotrabajosValidator(payload),
	infraestructuraValidator: (payload) => infraestructuraValidator(payload),
	infraestructuradetalleValidator: (payload) => infraestructuradetalleValidator(payload),
	infraestructuraubicacionValidator: (payload) => infraestructuraubicacionValidator(payload),
	negocioValidator: (payload) => negocioValidator(payload),
	negociodetalleValidator: (payload) => negociodetalleValidator(payload),
	negocioordenValidator: (payload) => negocioordenValidator(payload),
	negocioservicioValidator: (payload) => negocioservicioValidator(payload),
	ordenValidator: (payload) => ordenValidator(payload),
	ordendetalleValidator: (payload) => ordendetalleValidator(payload),
	ordenservicioValidator: (payload) => ordenservicioValidator(payload),
	servicioValidator: (payload) => servicioValidator(payload),
	serviciodetalleValidator: (payload) => serviciodetalleValidator(payload),
	tipoareaValidator: (payload) => tipoareaValidator(payload),
	tipocargoValidator: (payload) => tipocargoValidator(payload),
	tipoclienteValidator: (payload) => tipoclienteValidator(payload),
	tipodivisionValidator: (payload) => tipodivisionValidator(payload),
	tipoequipamientoValidator: (payload) => tipoequipamientoValidator(payload),
	tipoinfraestructuraValidator: (payload) => tipoinfraestructuraValidator(payload),
	tiponegocioValidator: (payload) => tiponegocioValidator(payload),
	tipoordenValidator: (payload) => tipoordenValidator(payload),
	tiposervicioValidator: (payload) => tiposervicioValidator(payload),
	tipoubicacionValidator: (payload) => tipoubicacionValidator(payload),
	tipousuarioValidator: (payload) => tipousuarioValidator(payload),
	ubicacionValidator: (payload) => ubicacionValidator(payload),
	usuarioValidator: (payload) => usuarioValidator(payload),
	usuariologinValidator: (payload) => usuariologinValidator(payload),
}

module.exports = validator
